# Generated by Django 6.0.1 on 2026-01-23 06:54

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='accounts',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='accounts',
            name='username',
            field=models.CharField(default='user', max_length=150),
        ),
    ]
